### ISSUE TITLE
Print tensors to text file?

### ISSUE THREAD

**Issue by dza6549** [tkalayci71/embedding-inspector#10]
Hi, 

thank you for releasing this very fun extension. Is it possible to print tensor ranges to a text file? When I use the https://github.com/CodeExplode/stable-diffusion-webui-embedding-editor I can see the upper and lower limits of the tensor in the source code. I think the sliders are given min/max values from somewhere and I'm guessing it is from the tensor? The value in that other extension Embeddings Editor appears to correspond to the (rounded up) value printed in your Embedding Inspector extension.

Do you know of any official discussion about mixing or our we all in new territory here? You write "but what each number controls is a mystery" :) I would like, for example, to compare the tokens "red" and "shirt" with an embedding (concat and 1vec) of "red shirt" to look for tensor min/max/midpoint overlap 

In embedding_inspector.py I can see VEC_SHOW_TRESHOLD = 1 and torch.set_printoptions(threshold=VEC_SHOW_TRESHOLD,profile='default') - this is for the parent vector? Is there something similar for each tensor - e.g. Min/Max/Rounded Midpoint?

I guess the tensors are being printed with this results.append('Vector['+str(v)+'] = '+str(vec_v)) but I am not clear how I might get more details.

Thank you for your time.

Cheers

**Comment by tkalayci71** [comment]
Hi,

If you change it to VEC_SHOW_TRESHOLD = 10000, all values should be shown, and profile='full' should display more precision. For saving to file, you could add the following code below the "all_embs = ..."  line.

```
    with open('emb_vec.txt', 'w') as f:
        f.write(str(emb_vec))
        f.close()

```
the file should be saved in webui folder. 

However, I doubt any of this will be useful. I tried shifting all the numbers to positive range with no effect, and zeroing most of the values in cat emb but still getting cat pictures. It's fun but I couldn't find a pattern or logic. What I know mostly comes from the video linked on embedding editor page, so I don't have good answers for you, but thanks and happy new year

**Comment by dza6549** [comment]
Thank you for your reply. I shall try the print code. I was after the values of the tensors inside the vector. I can't see them all in the text box. They are abbreviated e.g. `Vector[0] = tensor([-0.0091,  0.0009, -0.0034,  ..., -0.0360, -0.0135,  0.0065])` - ideally I'd like to save all of the 768 tensors at 20(?) digit precision.

If you could give a hint on a direction to list the tensors I'd be very appreciate.

The max/min values may be irrelevant after all and may be a product of the other extension I was playing with. Have you seen this really interesting discussion? https://github.com/CodeExplode/stable-diffusion-webui-embedding-editor/issues/3 The poster says he's able to turn off arms and legs etc. 

Cheers and happy Festivus!

**Comment by dza6549** [comment]
Did it in the other guy's extension with your code. Thank you!

```
    # save hack in embedding_editor.py Line 253
    with open('emb_tensors.txt', 'w') as f:
        f.write(str(weights))
        f.close()
```

**Comment by CodeExplode** [comment]
Glad that you got it working. The min/max values for each weight are just the min/max of all the existing embeddings in the dictionary (about 49,000 of them), which seemed like a good boundary for all the concepts which SD understands.

With weighting an embedding can be pushed outside of there and still works. The original textual inversion author mentioned that an embedding's editability is expected to be much higher for embeddings which are within the original distribution of values which the model was trained on, which was the main motivation.

**Comment by dza6549** [comment]
Whoa. Just raised a ticket and your reply here is blowing my mind after the first 15 words! :) Must now take time to process. I can't see the colours on the sliders yet, and the idea that you are going though the list of tokens for each slider is too much for my tiny mind. I think I understand about 0.049026597291231155% of your words. Thank you for taking the time.
Cheers
