### ISSUE TITLE
Resize Embedding when vector's magnitude = 0

### ISSUE THREAD

**Issue by klsic** [tkalayci71/embedding-inspector#11]
would it be possible to overwrite an embedding if the vector is zerod out?

= v * 1.0 * (n==0) + v * **0.0 * (n==2)** + v * 0.5 * (n==2)

So that I can get rid of the 2nd vector?

**Comment by tkalayci71** [comment]
Just uploaded a quick fix for this, please test and close issue if it works, thank you.

**Comment by klsic** [comment]
works great! thank you!
