### ISSUE TITLE
A feature request and a thank you!

### ISSUE THREAD

**Issue by SanDiegoDude** [tkalayci71/embedding-inspector#12]
Hey there, I make 2.x embeddings and your extension has been instrumental to the creation of all of my released embeddings: https://civitai.com/user/SoCalGuitarist

I just want to give a hearty thank you for creating this tool, and I'm excited to see what changes you make moving forward.  One thing I'd love to be able to do is the ability to excise vectors out of embeddings. Is this something that could possibly added? It's the one missing piece I need for my embeddings, and would really make your tool feature complete in my eyes.

 Thanks again!!!

**Comment by tkalayci71** [comment]
Hi, you're welcome, I'm glad it's useful, thanks.

What exactly do you mean by excise vectors?

**Comment by SanDiegoDude** [comment]
I mean I'd like to be able to remove individual vectors from within an embedding. For example, I have an embedding that's really good, but it loves to put jackets and hoodies on everything. Looking under the hood using your inspector, I can see a vector that is responsible for the bad behavior and would like to be able to "subtract" it from the overall embedding, preferably by removing reference to the vector completely if possible. I saw a user reference doing this over on CivitAI's discord page here:  https://discord.com/channels/1037799583784370196/1037799583784370202/1058416690079211560 talking about using the eval box to trim vectors, and have asked him for more information on what he's doing, because if he's found a way to do it through eval, then it's something your tool can do already and maybe just made a lil easier in UI...

**Comment by tkalayci71** [comment]
Oh I see. Currently you can do that with eval, for example enter  =v* (n!=2) to remove 2nd vector, or =v* (n!=3 and n!=5) to remove 3th and 5th vectors, etc. I can add a box in which you enter like 2, 3, 5. Checkboxes would be better but I haven't found a way to create checkboxes dynamically.

**Comment by SanDiegoDude** [comment]
Heck, even just a tooltip that explains what you described here would go a long way, I had no clue how to call the vectors as variables.  Excellent!

**Comment by tkalayci71** [comment]
I know the interface is messy and documentation poor. Hopefully it will improve in the next year. Happy new year!

**Comment by SanDiegoDude** [comment]
It's a wonderful tool and incredibly powerful, especially in 2.X. Thanks again for putting in the effort!
