### ISSUE TITLE
No issue, just a thanks for adding the Save vector to text button

### ISSUE THREAD

**Issue by dza6549** [tkalayci71/embedding-inspector#13]
Thanks! :)

I'm going to try to hack a load text file to vector function and will let you know if I find something. Your eval() functionality is very helpful and built into the GUI, and I'd like to do something similar with Excel for plotting and easy vector/embedding comparison. 

Best wishes for 2023 @tkalayci71 

Cheers

**Comment by dza6549** [comment]
Closing but happy to discuss a load function further if you have any advice :)

**Comment by tkalayci71** [comment]
I've been playing with some eval functions, and with this I can reduce each number to effectively 1-bit (dividing by 50 to adjust magnitude)

=( 1* (v>=0)-1* (v<0) ) /50 

some details are lost but amazingly it still works. (tried for some internal embeddings like "cat" and "clown", SD1.4)

Also I've come up with an analogy that embeddings are like DNA, and mixing/modifying them is like genetic engineering :)

Thanks and my best wishes!

**Comment by tkalayci71** [comment]
you can probably load from text file, assuming the text starts with tensor([
```
    with open(fnam, 'r') as f:
        lines = f.readlines()
        f.close()
    s = ''.join(lines)
    emb_vec = eval('torch.'+s).to(device='cpu',dtype=torch.float32)
    print(emb_vec.shape)

```
success if this prints torch.Size([1, 768])
