### ISSUE TITLE
No issue (again) just want to say the one-bit binary eval function is incredibly powerful

### ISSUE THREAD

**Issue by dza6549** [tkalayci71/embedding-inspector#15]
Thanks once again @tkalayci71!
I mixed the tokens 'green' and 'eyes' and it worked. 
I think this will be an incredibly powerful technique for analysing and controlling image characteristics, and removing some of the randomness in SD generation. (I do like the random element as well. Waiting for the image to denoise is remarkably entertaining:)
Cheers!

**Comment by dza6549** [comment]
**This is incredible! DNA/Morse code!**

I woke up at 1:38am and realised that the bit eval was like a string of Morse code (or DNA :) ), or directions for travelling through a maze. "Go left, then right, then right, then left, then left again, the right. If you travel this path you will find a sad little kitten with green eyes"

Do you know if there is a limit to the number of tokens that can be embedded in a 1vec? My very limited testing suggests a limit of 3 tokens - at least with this kitten example. 

Can we determine what tokens are assigned to what vectors in a mixing concat operation? I will try anyway.

Now your DNA idea - is a specific part of the 768 bit string responsible for paws, eyes, ears, sadness? I guess one could try a 'gene splice' and zero parts of the string. So instead of 0.0199999995529651 or -0.0199999995529651 we could set the tensor to 0?

Thanks again @tkalayci71 - great way to be entertained during holidays!

**Eval func**
```
File already exists, overwrite is enabled
+ kitten</w>(13063) x 1
+ green</w>(1901) x 1
+ eyes</w>(3095) x 1
Applied eval: "=( 1* (v>=0)-1* (v<0) ) /50"
Saved "embeddings/kitten.bin"

```
**Result images**
![1](https://user-images.githubusercontent.com/27390320/210260659-c2027e0e-b921-48b5-b4ac-dacd345ea3be.png)

![2](https://user-images.githubusercontent.com/27390320/210260677-375adcb6-232c-4f18-aa9f-5d591496955b.png)

**Scatter plot**
![kitten-morse](https://user-images.githubusercontent.com/27390320/210260439-d50493ad-dee8-449f-bf40-8331569e8d64.PNG)

**Scatter plot detail**
![kitten-dna](https://user-images.githubusercontent.com/27390320/210261028-ad4e501a-ac14-4a5e-967e-389b69b8db24.PNG)

**Comment by tkalayci71** [comment]
Hi, yes, reducing to 1-bit simplifies things quite a bit (still, 2^768 is huge number) I'm amazed it even works, let alone if mixing also works. There must be a limit, I don't know how many more tokens can fit in there (however I must also note that getting a cat with anything but green eyes is hard). 

> Can we determine what tokens are assigned to what vectors in a mixing concat operation? I will try anyway.
not sure what you meant here

> is a specific part of the 768 bit string responsible for paws, eyes, ears, sadness? I guess one could try a 'gene splice' and zero parts of the string
That is the big question..  zeroing parts with eval is already easy like with =v* (i<300). Another thing, how does cat DNA compare to dog DNA, what parts are common/different, that might give useful info. I'm kind of overwhelmed now, but good luck with your experiments, we're closer to cracking this code.  Best wishes!

**Comment by tkalayci71** [comment]
Here's an idea that might help:

Replace eval presets in the script with:

```
EVAL_PRESETS = ['None','',
    'bin0-100',
    '=((1*(v>=0)-1*(v<0))*(i>0)*(i<100))/20',
    'bin100-200',
    '=((1*(v>=0)-1*(v<0))*(i>100)*(i<200))/20',
    'bin200-300',
    '=((1*(v>=0)-1*(v<0))*(i>200)*(i<300))/20',
    'bin300-400',
    '=((1*(v>=0)-1*(v<0))*(i>300)*(i<400))/20',
    'bin400-500',
    '=((1*(v>=0)-1*(v<0))*(i>400)*(i<500))/20',
    'bin500-600',
    '=((1*(v>=0)-1*(v<0))*(i>500)*(i<600))/20',
    'bin600-700',
    '=((1*(v>=0)-1*(v<0))*(i>500)*(i<600))/20',
    'bin700-800',
    '=((1*(v>=0)-1*(v<0))*(i>700)*(i<800))/20'
    ]

```

check "Save for ALL presets" option. This will save 9 embeddings.

then use "prompts from file or textbox" script with this text:

test
test_bin0-100
test_bin100-200
test_bin200-300
test_bin300-400
test_bin400-500
test_bin500-600
test_bin600-700
test_bin700-800

(check "Use same random seed for all lines")

I thought this may help automate. Cheers!

**Comment by dza6549** [comment]
Yes kitten with green eyes is textbook confirmation bias!

Back at work now so will have less time to play unfortunately.

Thanks for the filter code. Works as expected.

![kitten-100](https://user-images.githubusercontent.com/27390320/210415922-9e670348-071d-40a9-925e-74de3bcf882c.PNG)

Scary thing though. Still produces kitten like things with just 100 tensors.

![10260-202301040503103995947121](https://user-images.githubusercontent.com/27390320/210416040-f8d78e7e-e6ca-4206-ba83-356d99d6339f.png)

![leo-pointing2](https://user-images.githubusercontent.com/27390320/210416272-350eabcb-8fb0-4350-8b44-f92fc6a06f18.png)

Have a good one @tkalayci71 Later!
