### ISSUE TITLE
Feature Request: Show strengths of related tokens under "Similar embeddings:"

### ISSUE THREAD

**Issue by ProGamerGov** [tkalayci71/embedding-inspector#16]
I think it would be useful to see the strengths of related tokens under the "Similar embeddings:" section, as currently its hard to gauge the level of similarity.

This feature might need to be select-able via a button or something though, to not clutter the UI.

You might also want to change the sections title from "Similar embeddings:" to "Similar tokens:", unless I'm missing something important. Similarily, the mixer should say "Enter name of embedding or token id to mix" instead of just "Enter name of embedding to mix".

**Comment by tkalayci71** [comment]
Noted for future updates. Thank you.

**Comment by tkalayci71** [comment]
Implemented in v2.8 (however you need to modify the script as SHOW_SIMILARITY_SCORE = True)
Thanks again.
