### ISSUE TITLE
Awesome tool. Can you verify this. When we train a new embedding, does embedding name makes any difference? ohwx vs myawesomeimage

### ISSUE THREAD

**Issue by FurkanGozukara** [tkalayci71/embedding-inspector#24]
When we use myawesomeimage in reguler txt2img , it gets split into sub tokens

But what if we train a new embedding with myawesomeimage and use it in the txt2img tab to activate embedding, does it still split into sub tokens as usually or it is specially treated? How it works exactly?

So would there be any difference between using embedding name as ohwx with 4 vectors vs myawesomeimage with 4 vectors and zeroed vectors in the beginning 

Thank you very much for answers

**Comment by tkalayci71** [comment]
Hi, and thanks :)

I don't have much experience with training, but the embedding name (which is the file name) makes no difference, you can change it with no effect. Embedding name will not be tokenized, it will just activate the vectors in it and the number of vectors will take away from the 75 token limit. However, the initialization text you enter while creating the embedding gets tokenized, and if it has more tokens than the number of vectors, those tokens will be discarded, as far as I know.

**Comment by FurkanGozukara** [comment]
> Hi, and thanks :)
> 
> I don't have much experience with training, but the embedding name (which is the file name) makes no difference, you can change it with no effect. Embedding name will not be tokenized, it will just activate the vectors in it and the number of vectors will take away from the 75 token limit. However, the initialization text you enter while creating the embedding gets tokenized, and if it has more tokens than the number of vectors, those tokens will be discarded, as far as I know.

thank you. very well explanation

**Comment by tkalayci71** [comment]
I don't have those but feel free to contact via https://old.reddit.com/user/oeh123/
