### ISSUE TITLE
How can we see how many vectors in the selected model?

### ISSUE THREAD

**Issue by FurkanGozukara** [tkalayci71/embedding-inspector#25]
Could we extract all vector names and save into a file?
Also Magnitude means average weights of all vectors in the selected token?
Can we display / extract all vector weights of selected token?

Thank you very much

**Comment by tkalayci71** [comment]
> How can we see how many vectors in the selected model?

there are 49408 tokens and each contain 1 vector (size is 768 for SD1, 1024 for SD2 )

> Could we extract all vector names and save into a file? 

you can download vocab.json from

https://huggingface.co/openai/clip-vit-large-patch14/tree/main

vocabulary sholud be the same for SD2

> Also Magnitude means average weights of all vectors in the selected token? 

For each vector a separate magnitude is displayed (which is square root of sum of squares of 768 values)
you may need to scroll the textbox if other vectors aren't visible

> Can we display / extract all vector weights of selected token?

"Save vector to text file" button should do that

**Comment by FurkanGozukara** [comment]
@tkalayci71 ty so much great answers
