### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by tboronczyk** [tkalayci71/embedding-inspector#26]
When attempting to use the extension, typing "cat" in the inspect field and clicking the inspect button, it crashes. The console reports:

2023-02-20 19:44:08.448 Python[29940:9903674] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001aa2351a8 __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001a9f7fe04 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001aa260128 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x00000001acd43930 -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 372
	4   AppKit                              0x00000001acd2e92c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 948
	5   AppKit                              0x00000001acd2e56c -[NSWindow initWithContentRect:styleMask:backing:defer:] + 56
	6   _macosx.cpython-310-darwin.so       0x0000000178e2c8c4 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 52
	7   _macosx.cpython-310-darwin.so       0x0000000178e2fdbc FigureManager_init + 224
	8   Python                              0x000000010171d810 wrap_init + 20
	9   Python                              0x0000000101695bac wrapperdescr_call + 396
	10  Python                              0x0000000101688d3c _PyObject_MakeTpCall + 136
	11  Python                              0x00000001017bf084 call_function + 380
	12  Python                              0x00000001017b72bc _PyEval_EvalFrameDefault + 23768
	13  Python                              0x00000001017afd58 _PyEval_Vector + 360
	14  Python                              0x0000000101688ff4 _PyObject_FastCallDictTstate + 96
	15  Python                              0x000000010171d640 slot_tp_init + 196
	16  Python                              0x0000000101714440 type_call + 312
	17  Python                              0x0000000101688d3c _PyObject_MakeTpCall + 136
	18  Python                              0x00000001017bf084 call_function + 380
	19  Python                              0x00000001017b59b4 _PyEval_EvalFrameDefault + 17360
	20  Python                              0x00000001017afd58 _PyEval_Vector + 360
	21  Python                              0x000000010168cc04 method_vectorcall + 124
	22  Python                              0x00000001017bef8c call_function + 132
	23  Python                              0x00000001017b72bc _PyEval_EvalFrameDefault + 23768
	24  Python                              0x00000001017afd58 _PyEval_Vector + 360
	25  Python                              0x000000010168cc04 method_vectorcall + 124
	26  Python                              0x00000001017bef8c call_function + 132
	27  Python                              0x00000001017b72bc _PyEval_EvalFrameDefault + 23768
	28  Python                              0x00000001017afd58 _PyEval_Vector + 360
	29  Python                              0x000000010168cc04 method_vectorcall + 124
	30  Python                              0x00000001017bef8c call_function + 132
	31  Python                              0x00000001017b72bc _PyEval_EvalFrameDefault + 23768
	32  Python                              0x00000001017afd58 _PyEval_Vector + 360
	33  Python                              0x000000010168cc04 method_vectorcall + 124
	34  Python                              0x0000000101689844 PyVectorcall_Call + 140
	35  Python                              0x00000001017b1ba4 _PyEval_EvalFrameDefault + 1472
	36  Python                              0x00000001017afd58 _PyEval_Vector + 360
	37  Python                              0x0000000101689844 PyVectorcall_Call + 140
	38  Python                              0x00000001017b1ba4 _PyEval_EvalFrameDefault + 1472
	39  Python                              0x00000001017afd58 _PyEval_Vector + 360
	40  Python                              0x00000001017b1ba4 _PyEval_EvalFrameDefault + 1472
	41  Python                              0x00000001017afd58 _PyEval_Vector + 360
	42  Python                              0x00000001017bef8c call_function + 132
	43  Python                              0x00000001017b72bc _PyEval_EvalFrameDefault + 23768
	44  Python                              0x00000001017afd58 _PyEval_Vector + 360
	45  Python                              0x00000001017dd11c _PyObject_VectorcallTstate.4665 + 96
	46  Python                              0x00000001017dcf78 context_run + 92
	47  Python                              0x00000001016f0bec cfunction_vectorcall_FASTCALL_KEYWORDS + 84
	48  Python                              0x00000001017b1ba4 _PyEval_EvalFrameDefault + 1472
	49  Python                              0x00000001017afd58 _PyEval_Vector + 360
	50  Python                              0x00000001017bef8c call_function + 132
	51  Python                              0x00000001017b62c8 _PyEval_EvalFrameDefault + 19684
	52  Python                              0x00000001017afd58 _PyEval_Vector + 360
	53  Python                              0x00000001017bef8c call_function + 132
	54  Python                              0x00000001017b62c8 _PyEval_EvalFrameDefault + 19684
	55  Python                              0x00000001017afd58 _PyEval_Vector + 360
	56  Python                              0x000000010168cd0c method_vectorcall + 388
	57  Python                              0x00000001018ad2e0 thread_run + 172
	58  Python                              0x00000001018302a8 pythread_wrapper + 48
	59  libsystem_pthread.dylib             0x00000001aa0e826c _pthread_start + 148
	60  libsystem_pthread.dylib             0x00000001aa0e308c thread_start + 8
)
libc++abi: terminating with uncaught exception of type NSException

**Comment by tkalayci71** [comment]
Hi, I can't reproduce the issue here, but it seems to be caused by matplotlib. As a workaround, please try to edit the script and change line 23 to "ENABLE_GRAPH = False", then click Reload UI button in Settings tab. Graph won't be plotted but it's not essential.

**Comment by tboronczyk** [comment]
thank you. that avoids the error
