### ISSUE TITLE
Inspecting an embed completely crashes Python on Mac

### ISSUE THREAD

**Issue by kayzen-ml** [tkalayci71/embedding-inspector#30]
Hi, thanks for your extension. Sadly after several attempts, it completely crashes Python (not only the WebUI but also Python itself!). It as apparently linked to memory usage. I'm on a M1 Pro Macbook Pro 16 GB. Here is the log, any idea to bypass this please? Thank you!

`/AppleInternal/Library/BuildRoots/c651a45f-806e-11ed-a221-7ef33c48bc85/Library/Caches/com.apple.xbs/Sources/MetalPerformanceShaders/MPSCore/Types/MPSNDArray.mm:794: failed assertion `[MPSNDArray, initWithBuffer:descriptor:] Error: buffer is not large enough. Must be 151781376 bytes
`

**Comment by tkalayci71** [comment]
Hi, I'm sorry for this issue, I don't have a Mac so I'm unable to debug it here. Only, if this crash occurs consistently, I can insert print statements and then you could tell me the console output, so we can maybe find the part where it occurs. Please let me know if you can spare time to help debug this, thanks.

**Comment by JuanuMusic** [comment]
I'm also experiencing the same issue.

> Only, if this crash occurs consistently,

It does :)

> I can insert print statements and then you could tell me the console output, so we can maybe find the part where it occurs. Please let me know if you can spare time to help debug this, thanks.

If you add some debug methods I can help debugging too and (if possible) attempt to fix and push a PR.

**Comment by tkalayci71** [comment]
> If you add some debug methods I can help debugging too and (if possible) attempt to fix and push a PR.

Hi, that would be great help. I was thinking of just adding print lines after each line to locate the crash, but maybe that won't be needed if you already see the console output with line numbers? or otherwise instead of prints should I write line numbers to a file? thanks

**Comment by don1138** [comment]
Device: 32Gb M1 Max Macbook
OS: Ventura 13.2.1
python: 3.10.10
torch: 1.13.1
xformers: N/A
gradio: 3.16.2
commit: [0cc0ee1b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/0cc0ee1bcb4c24a8c9715f66cede06601bfc00c8)
checkpoint: [4199a95566](https://google.com/search?q=4199a95566efba4cb751800a3d8a3779e9c438f07c391fe5d581e62b55b6f4d3)

Same issue.

In case it is useful, here's the terminal output:
```
2023-03-11 18:12:41.753 Python[17961:392974] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001a3ccc3e8 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x00000001a3816ea8 objc_exception_throw + 60
	2   CoreFoundation                      0x00000001a3cf5800 _CFBundleGetValueForInfoKey + 0
	3   AppKit                              0x00000001a6ef865c -[NSWindow(NSWindow_Theme) _postWindowNeedsToResetDragMarginsUnlessPostingDisabled] + 320
	4   AppKit                              0x00000001a6ee694c -[NSWindow _initContent:styleMask:backing:defer:contentView:] + 816
	5   AppKit                              0x00000001a6ee6610 -[NSWindow initWithContentRect:styleMask:backing:defer:] + 48
	6   _macosx.cpython-310-darwin.so       0x000000016fd5c9d8 -[Window initWithContentRect:styleMask:backing:defer:withManager:] + 52
	7   _macosx.cpython-310-darwin.so       0x000000016fd5fc14 FigureManager_init + 224
	8   Python                              0x0000000105398c8c wrap_init + 20
	9   Python                              0x000000010532d834 wrapperdescr_call + 400
	10  Python                              0x0000000105322c44 _PyObject_MakeTpCall + 136
	11  Python                              0x000000010541cd88 call_function + 272
	12  Python                              0x000000010541a510 _PyEval_EvalFrameDefault + 43104
	13  Python                              0x000000010540ea5c _PyEval_Vector + 376
	14  Python                              0x0000000105322eac _PyObject_FastCallDictTstate + 96
	15  Python                              0x0000000105398abc slot_tp_init + 196
	16  Python                              0x0000000105390a8c type_call + 288
	17  Python                              0x0000000105322c44 _PyObject_MakeTpCall + 136
	18  Python                              0x000000010541cd88 call_function + 272
	19  Python                              0x000000010541a538 _PyEval_EvalFrameDefault + 43144
	20  Python                              0x000000010540ea5c _PyEval_Vector + 376
	21  Python                              0x0000000105325eb0 method_vectorcall + 124
	22  Python                              0x000000010541ccf8 call_function + 128
	23  Python                              0x000000010541a510 _PyEval_EvalFrameDefault + 43104
	24  Python                              0x000000010540ea5c _PyEval_Vector + 376
	25  Python                              0x0000000105325eb0 method_vectorcall + 124
	26  Python                              0x000000010541ccf8 call_function + 128
	27  Python                              0x000000010541a510 _PyEval_EvalFrameDefault + 43104
	28  Python                              0x000000010540ea5c _PyEval_Vector + 376
	29  Python                              0x0000000105325eb0 method_vectorcall + 124
	30  Python                              0x000000010541ccf8 call_function + 128
	31  Python                              0x000000010541a510 _PyEval_EvalFrameDefault + 43104
	32  Python                              0x000000010540ea5c _PyEval_Vector + 376
	33  Python                              0x0000000105325eb0 method_vectorcall + 124
	34  Python                              0x000000010532348c PyVectorcall_Call + 184
	35  Python                              0x000000010541a6d8 _PyEval_EvalFrameDefault + 43560
	36  Python                              0x000000010540ea5c _PyEval_Vector + 376
	37  Python                              0x000000010532348c PyVectorcall_Call + 184
	38  Python                              0x000000010541a6d8 _PyEval_EvalFrameDefault + 43560
	39  Python                              0x000000010540ea5c _PyEval_Vector + 376
	40  Python                              0x000000010541a6d8 _PyEval_EvalFrameDefault + 43560
	41  Python                              0x000000010540ea5c _PyEval_Vector + 376
	42  Python                              0x000000010541ccf8 call_function + 128
	43  Python                              0x000000010541a510 _PyEval_EvalFrameDefault + 43104
	44  Python                              0x000000010540ea5c _PyEval_Vector + 376
	45  Python                              0x00000001054352e4 _PyObject_VectorcallTstate.4671 + 96
	46  Python                              0x0000000105435198 context_run + 92
	47  Python                              0x0000000105374ccc cfunction_vectorcall_FASTCALL_KEYWORDS + 84
	48  Python                              0x000000010541a6d8 _PyEval_EvalFrameDefault + 43560
	49  Python                              0x000000010540ea5c _PyEval_Vector + 376
	50  Python                              0x000000010541ccf8 call_function + 128
	51  Python                              0x000000010541a498 _PyEval_EvalFrameDefault + 42984
	52  Python                              0x000000010540ea5c _PyEval_Vector + 376
	53  Python                              0x000000010541ccf8 call_function + 128
	54  Python                              0x000000010541a498 _PyEval_EvalFrameDefault + 42984
	55  Python                              0x000000010540ea5c _PyEval_Vector + 376
	56  Python                              0x0000000105325fb8 method_vectorcall + 388
	57  Python                              0x00000001054dcc44 thread_run + 120
	58  Python                              0x000000010547ba90 pythread_wrapper + 48
	59  libsystem_pthread.dylib             0x00000001a3b7206c _pthread_start + 148
	60  libsystem_pthread.dylib             0x00000001a3b6ce2c thread_start + 8
)
libc++abi: terminating with uncaught exception of type NSException
zsh: abort      ./webui.sh
```

**Comment by tkalayci71** [comment]
Sorry for the delay everyone.. Attached is a debug version of the script. It outputs to console and also to a file (debug_embins.txt), replace the script in the extension folder and inspect a token. I'm not even sure what to do with the result but it may provide a clue.. thanks..

[embedding_inspector_debug.zip](https://github.com/tkalayci71/embedding-inspector/files/10972344/embedding_inspector_debug.zip)

**Comment by kayzen-ml** [comment]
> Sorry for the delay everyone.. Attached is a debug version of the script. It outputs to console and also to a file (debug_embins.txt), replace the script in the extension folder and inspect a token. I'm not even sure what to do with the result but it may provide a clue.. thanks..
> 
> [embedding_inspector_debug.zip](https://github.com/tkalayci71/embedding-inspector/files/11008595/embedding_inspector_debug.zip)

Sorry for the late reply, I tried your debugged version but it still doesn't work. What is also weird is that after having created an embed with Save Mixed, it also crashes when I tried to use it after. It says `OverflowError: cannot convert float infinity to integer`.

Any idea why? I am frustrated being stuck like this, I'm pretty sure it's not a big deal but I can't figure out what's wrong in your code. Thanks a lot for your help

**Comment by tkalayci71** [comment]
Sorry for the late reply also. Debug version is supposed to save log to "debug_embins.txt", do you have such a file?
