### ISSUE TITLE
Mixed embedding can not be trained further. 

### ISSUE THREAD

**Issue by iceandstorm** [tkalayci71/embedding-inspector#31]
There is a set of problems: 
* files are .bin not .pt
* training even when selected, the bin file will end with the creation of a pt file - this mean now two files of the same name are in the folder and this breaks training (deleting any of them allow continuing)
* .bin to pt swap via renaming seems not to cause issues, then no other pt file is created. 
* the new pt file seems only hold 1 vector - regardless what the source had
* any training seems to discard the values of the mix and start from scratch

I tried 
* any combination of (concate mode / combine as 1-vector) 
* creating the mix and a differently named normal emb, and swap the "data/0"

Suspected problem: 
* the training does not know how many vectors are there, the information like the step size in the past seems to be missing. 

I would love to know if I did something wrong and how I could train a mix, or if it is a bug that could be solved. 

Thx

**Comment by tkalayci71** [comment]
I will look into this bug, thanks for reporting.

**Comment by iceandstorm** [comment]
Thank you very much! If you need something tested, let me know.

**Comment by tkalayci71** [comment]
Just a quick update: I found that if emb.bin and emb.pt files both exist, they both get loaded, but inspector may show one while txt2img uses the other, restarting webui may switch them, it's glitchy. So duplicate file names are bad, at least I should save .pt files instead of .bin (this is an easy fix, hardcoded in the script)

About training, I didn't test it much due to my low vram, but don't forget to enter a step value when you save. Please try again, after renaming .bin to .pt, eliminating duplicate filenames, and restarting webui. I will try to test training soon. Thanks for your patience.

**Comment by tkalayci71** [comment]
now changed save extension to .pt

**Comment by iceandstorm** [comment]
The change to .pt is good. 

Thanks for that! I tried this already. I explain what I wanted to do: 
1. I have a combination of tokens that I use a lot to get something close to the thing I want. (In that case a scfi body armor that looks heavily worn and damaged but is still functional) tokens I use are "armor" "scifi" "-1 medieval" .... in total 11 tokens, some positive, some negative some with reduced power) 
2. I created the mix, this part works perfect.
3. I want to train this mix further. It collapses to 1 vector. 

With renaming/restarting in between it keeps the vectors but after training the inspector changes the "most similar tokens" rapidly and the outputs even when only trained 5 steps are only chaos.

**Comment by tkalayci71** [comment]
So now with the change to .pt, you no longer need to rename/resart, and there's no collapse to 1 vector, right? 

Are you using concat mode? (which creates multiple vectors and is similar to entering Initialization text in training but you can also adjust weights) If not you can try that. 

Most similar tokens aren't really a concern but if the outputs are chaos.. I can't say why. Maybe the vector mangitudes are getting too large?
