### ISSUE TITLE
Embedding object has no attribute filename - solved!

### ISSUE THREAD

**Issue by Torcelllo** [tkalayci71/embedding-inspector#32]
This is the code produced

line 174, in do_inspect
    results.append('Filename: '+str(loaded_emb.filename))
AttributeError: 'Embedding' object has no attribute 'filename'

**Comment by tkalayci71** [comment]
Your webui may not be up to date but just uploaded a fix in either case, please try, thanks.

**Comment by Torcelllo** [comment]
It's OK now, thank you!
