### ISSUE TITLE
May I use your code for my own project?

### ISSUE THREAD

**Issue by Nekos4Lyfe** [tkalayci71/embedding-inspector#35]
Hi,
I have some ideas on additional features for modifying tokens. I have been using your code to implement "replace with similar tokens" feature using a numerical approach rather than comparing tokens in CLIP. 

In addition, token interpolation/ optimization and functionality to split embeddings into its vector parts. The code is not done yet, 
but it's getting there. I will use it for demonstration purposes on a post I am making on token optimization on civitai, which I will publish a week or so from now. 

Likely, people will want to test these modifications for themselves, so I will feel compelled provide a link to the modified script. 
I will of course credit you for providing the codebase and provide a link to this github project.  

Is this ok?

Kind regards/
Nekos4Lyfe

**Comment by tkalayci71** [comment]
Hi, you can do whatever you like with this (hence the Unlicense license). There's no need to give credit. But be warned that it doesn't work on Mac, reportedly. I have pretty much abandoned this extension.

Best of luck with your project.

**Comment by Nekos4Lyfe** [comment]
Glad to hear it! I'll make sure to mention the Mac issue in my post. Thanks (; v ;)b!
