### ISSUE TITLE
Inspecting text only lists single vector.

### ISSUE THREAD

**Issue by klsic** [tkalayci71/embedding-inspector#6]
Something changed since the update, it used to display all vectors.

**Comment by tkalayci71** [comment]
Hi, I can't seem to reproduce this issue. did you try scrolling the text with mouse wheel, or resize the box?

**Comment by klsic** [comment]
Yea.  It always returns vector count 1.  Seems to cleave the first token and ignores the rest.  Does the same thing when I put in local embeddings.

Text Input: edrgergsdfgsdfgergerg435

Embedding name: "ed"
Embedding ID: 843 (internal)
Vector count: 1
Vector size: 1024
--------------------------------------------------------------------------------
Vector[0] = tensor([-0.0017,  0.0097, -0.0028,  ...,  0.0012, -0.0019, -0.0084])
Magnitude: 0.36713048815727234
Min, Max: -0.036529541015625, 0.035400390625

Similar embeddings:
ed(843)   ed</w>(538)   edo(29145)   edin(6524)   edition</w>(3062)   es(957)   jo(683)   edy(17072)   need(3229)   eb(12283)   ad(594)   end(945)   ced</w>(2323)   sd</w>(4159)   wed(1687)   fed(22518)   red(1893)   eli(1018)   cad(6297)   sd(3080)   ped(13197)   cade(10497)   gra(782)   med(1948)   el(544)   kad(10901)   smart(5383)   ago(6276)   id(1568)   pd(4387)

**Comment by tkalayci71** [comment]
yes, only first token is processed, this is expected. And also all internal embeddings have only 1 vector. But local embeddings can have multi vectors. Click 'List loaded embeddings' and see if there's any with multi vectors, copy&paste its name and inspect that, it should work. 

If you need to know all token ids in a text, enter that in 'mini tokenizer' and click tokenizer, see ids below. And you can inspect those numbers as #123, one at a time, However, only one embedding info can be displayed in the big info box above.

**Comment by klsic** [comment]
Ah gotcha, didn't realize I needed to load first.  Thank you.
