### ISSUE TITLE
Average function

### ISSUE THREAD

**Issue by DarkAlchy** [tkalayci71/embedding-inspector#7]
Apparently I need an averaging ability if I want to take my two embeddings I use (both are styles) and shove them into one.  I used this script to merge, concat, to 1 vector etc... and cannot get the same result out no matter what I have tried.

Any ideas?

**Comment by tkalayci71** [comment]
There's no guarantee that merging two embeddings will always work, but you can try mixing with different multipliers to find a good balance, this is the first way to mix. The second way is mixing different parts of them, which again requires a lot of trial and error. I would like to help but I would need the embedding files and know exactly what result you are expecting.

**Comment by DarkAlchy** [comment]
These formulas are so hard to read.  I know programming and these even made me pause.  This formula is even more esoteric so to begin to grasp this I need a few things, if you would be so kind.  #1 What kind of formulas are these as they seem as if they are a mix mash of programming shorthand intermixed with maths so I need a place to go to read about what is doing what.  #2 If I had six embeddings in the boxes (their multipliers all at 1 but doesn't matter with this) how do I create a formula each one?  Iow, I do not see in the formula where it is taking (emb 1 + emb 2)/2 or (emb 1 + emb 2 + emb 3)/3 etc...  fact is I don't see how it is working on more than one embedding with the eval period.

If I can get a grasp of how the eval really works, with what sort of formulas being used, and how it addresses each embedding I can work with it for sure.

Thank you.

**Comment by tkalayci71** [comment]
yeah sorry I realize this is a poor design.....

Eval string is in pyhton syntax, evaluated for each value in the vectors.  For example = v * 2 means new_value = old_value * 2

The embeddings are always first multiplied by the multipliers (this is hard-coded, before eval) then merged according to options.

For example suppose EmbA has 8 vectors and EmbB has 16 vectors,
Without concat mode: EmbA is padded with zeros to make it 16 vectors, then they are added and the result has 16 vectors.  So if you have 0.5 as multipliers, the result is the same as EmbA / 2 + EmbB / 2

With concat mode: no zero padding, they are just stacked and result has 24 vectors

Eval string is executed at this point. 

n is the vector number variable.  (n==0) is a boolean expression, returns 1 for True and 0 for False. Therefore v * (n==0) equals to v for first vector and equals to 0 for other vectors.

i is the index variable. For example (i<300) is a boolan expression equal to 1 or 0, depending on i lower than 300 or not. Again, multiplying this with v makes it equal to v or 0, depending on the index. ( (i % 2)==0 ) returns 1 or 0 depending on i being odd or even

Then, like, v * (n==0) * (i < 300) +  v * (n==1) * (i >= 300)     
first part is activated only when n is 0 , and second part activated only when n is 1, adding them gets the mixed result

Finally, if "combine as 1-vector" option is checked, the result is reduced to a single vector by adding them together. However, If you are reducing many 16-vector embeddings to just 1-vector, too much  of information gets lost, and I doubt it's gonna work well.  I think your final embedding should have multiple-vectors. What you can do is... you can first process each embedding separately, using eval strings (without any other options), save them with different filenames, then mix thoso saved files..

**Comment by DarkAlchy** [comment]
With you so far to eval string as that is how I figured it was working.

Good, I had it all correct all along, but what I still do not see is eval able to handle 2,3,... embeddings so we could manipulate the embedding's vectors using eval.

**Comment by tkalayci71** [comment]
> emb 1, vector 2 + emb 3 vector 5 + emb 2 vector 1, etc....

easy way to do that would be to first extract those vectors to new files, then mix them later

to extract emb1, vector 2: enter only emb1 name,  use eval string =v * (n==2)

**Comment by DarkAlchy** [comment]
> > emb 1, vector 2 + emb 3 vector 5 + emb 2 vector 1, etc....
> 
> easy way to do that would be to first extract those vectors to new files, then mix them later
> 
> to extract emb1, vector 2: enter only emb1 name, use eval string =v * (n==2)

Oh, iow your script can't yet do it.  Alright, I hope you will add this functionality when you get the time as it is a biggie instead of having to do the kludgey way.

**Comment by tkalayci71** [comment]
That's true, but adding eval boxes and more, for each embedding, would get too messy, bad as it is. 
I'm thinking of a separate "Embedding mixer" extension. Thanks for your suggestions.

**Comment by DarkAlchy** [comment]
> That's true, but adding eval boxes and more, for each embedding, would get too messy, bad as it is. I'm thinking of a separate "Embedding mixer" extension. Thanks for your suggestions.

That would rock.  As far as messy the entire Automatic1111 WebUI is absolutely the worst UI I have ever seen to begin with, but if you feel another extension is needed then cool.  Btw, the one this is based upon no longer works as I tried and it just bombs out.  Known issue Automatic changed something but no fix yet for over 3 weeks.
