### ISSUE TITLE
Could you add a button to reset the embedding mixer on the right side of the page.

### ISSUE THREAD

**Issue by klsic** [tkalayci71/embedding-inspector#8]
Just a QOL request.  Thanks for the addon, its so useful.

**Comment by tkalayci71** [comment]
sure, as soon as I have time. should it reset everything (including filename, options) or just the top part?

**Comment by klsic** [comment]
I guess just the top.  It's only deleting all the fields and reseting the sliders that's annoying lol.  Thanks a bunch man.
