### ISSUE TITLE
Just not adding up.

### ISSUE THREAD

**Issue by DarkAlchy** [tkalayci71/embedding-inspector#9]
I keep running into this where your extension will say I have only one vector, but I told it 8,16,24, or 32.  I go back to check and the slider is where it should be.  I then look at the file size and the file size is right for the number of vectors I said.

I wonder what is going on?

65k = 16 vectors, 33k = 8, etc... and the embedding works.

**Comment by tkalayci71** [comment]
I'm unable to reproduce this. It may be showing an internal emb if you misspell the name, did you try copy&pasting the name from the listed loaded embeddings? I also checked embedding names with spaces and unicode emojis, and it works here. I would need an example file.

**Comment by DarkAlchy** [comment]
I sure did and this happens far more often than it doesn't happen.  It isn't on my side as the embedding is fine it just stops with the first vector so your extensions shows them as just one vector.

**Comment by tkalayci71** [comment]
I will attend to this and other bugs next week. Happy new year

**Comment by DarkAlchy** [comment]
You as well.

**Comment by DarkAlchy** [comment]
![image](https://user-images.githubusercontent.com/10561690/209908771-cdfbc5dc-b9e2-483a-9bdb-62ccdd02d4a9.png)
![image](https://user-images.githubusercontent.com/10561690/209908815-c3db77ab-bc9f-490c-a802-f51747c1c2b9.png)

Thought these would help.

**Comment by tkalayci71** [comment]
Oh that explains it... Your filename starts with uppercase N, but inspecting with lowecase n. So I forgot to compare the names case insensitively, my bad, will fix as soon as possible. Thanks

**Comment by tkalayci71** [comment]
Uploaded the fix. Could you please test and close issue (if I didn't mess up)

**Comment by DarkAlchy** [comment]
Fixed.

Thank you.
